---
pages:
- posts/post-2.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: field_group_list
  name: product
  label: Product
  description: a product
- type: image_gallery
  name: images
  label: Images
  description: insert a range of images
